start-service:
	sudo cp download-nhk-radio.service /etc/systemd/system
	sudo systemctl enable download-nhk-radio.service
	sudo systemctl start download-nhk-radio.service

stop-service:
	sudo systemctl stop download-nhk-radio.service
	sudo systemctl disable download-nhk-radio.service
	sudo rm /etc/systemd/system/download-nhk-radio.service



